$("#truth").click(function() {
    var orders = [
        "Kapan terakhir kali ngompol?",
        " Momen paling memalukan apa yang kamu rasakan sebulan terakhir",
        "Kalau kamu bisa pilih kekuatan super, mau punya kekuatan apa?",
        "Kalau kamu bisa menghilang, apa hal pertama yang kamu lakukan?",
        "Kalau kamu bisa baca pikiran, pikiran siapa yang bakal kamu baca duluan?",
        "Berapa jam kamu tidur paling lama?",
        "Siapa celebrity crush kamu?",
        "Mimpi paling aneh yang pernah kamu alami?",
        "nama yang di kasih temen yang palimg konyol?",
        "Skenario paling aneh yang pernah terlintas di pikiranmu tentang kita?",
        "Video TikTok atau YouTube paling memalukan yang pernah kamu tonton?",
        "pernah ada niatan nyembah kasur?",
        " Cerita Wattpad/fan fiction/buku paling memalukan yang pernah kamu baca?",
        " Kalau kamu cuma bisa makan satu jenis makanan seumur hidup, mau makan apa?",
        "apa yang akan lo lakukan , kalau semua orang tiba tiba jadi zombie?",
        "siapa mantan yang paling berengsek di dalam kisah cinta lo?",
        "Hal kecil apa yang pernah dilakukan ortu dan bikin kamu senang banget?",
        "Apa kartun favorit kamu pas kecil?",
        "kenapa spongebob kotak",
        "Kalau bisa jadi tokoh fiksi selama sehari, mau jadi apa?",
        "kalau dunia ini tanpa dosa dan hukum, apa yang akan lo lakuin ?",
        "Siapa orang terakhir yang kamu stalking di media sosial?",
        "Kalau ada jin kasih kamu tiga permintaan, mau minta apa aja? ",
        "kapan terakhiur kali lo minta duit ke ortu?",
        "Apa love language kamu?",
        "udah follow ig gw belom? follow yuk @blankbrains",
        "apa mimpi lo yang pengen banget terwujud?",
        "menurut lo gimana kondisi indonesia sekarang?",
        "Apa quotes favoritmu?",
        "pernah gak lo dapet motivasi yang bikin diri lo berubah jadi lebih baik?",
        "Artis atau lagu apa yang paling sering kamu putar pas lagi down?",
        "Apa insecurity terbesarmu?",
        "gimana kondisi lo sekarang(sedih/bahagia/dll) ceritakan sama temen yang lagi main ini sama lo?",
        "Kapan terakhir kali bohong ke orang tua? dan bohong hal apa",
        "Hal apa yang kamu harapkan bisa kamu ubah dari diri sendiri?",
        "Kapan terakhir kali bohong? (Dilarang bilang ”Aku gak pernah bohong, nah itu aku baru bohong“)",
        " Kapan terakhir kali menangis? and karena hal apa",
        "Apa ketakutan terbesarmu? (ceritakan sama temen yang lo ajak main ini)",
        "pertama kali ciuman sama orang lain kapan?",
        "ceritain hal yang paling bikin lo kesel dari orang yang lagi main ini sama lo ?",
        "Apa penyesalan terbesarmu? (ceritakan sama temen yang lo ajak main ini)",
        "Kalau kamu nggak bisa ketemu kita lagi besok, apa yang mau kamu sampaikan atau lakukan?",
        "Siapa nih crush rahasia kamu?",
        "Punya berapa crush selama hidup?",
        "Baca chat terakhir yang kamu kirim ke sahabat.",
        "kasih liat chat wa terakhir yang lo kirim ke orang (kasih liat ke temen lo yang main ini sama lo)",
        "hal apa yang kamu harap daroi oratu bisa ubah dari dirinya",
        "Apa yang kita nggak tahu pernah terjadi di antara kamu sama mantan kamu?",
        "Di antara pemain, siapa yang paling dekat atau paling tahu banyak tentang kamu?",
        "First impression kamu tentang orang yang ada di sebelah lu?",
        " Rate temen yanbg di sebelah lo dari skala 1-10",
    ];
    var order = orders[Math.floor(Math.random() * orders.length)];
    $("#result").html(order);
});



$("#dare").click(function() {
    var dares = [
        "Baca/buat puisi dengan tema (alam/cinta/sesuatu yang absurd) selama dua menit.",
        "Kasih Instagram kamu ke (nama orang) selama dua jam..",
        "Kasih ponsel ke (nama orang) dan dia bebas mau kirim satu pesan untuk satu orang.",
        "senyumin orang gak dikenal sebanyak 3 orang",
        "Break dance.",
        "Jadi kucing sampai dapat giliran lagi",
        " Pamer deh gerakan dance terbaikmu.",
        "nyanyi lagu manuk dadli yang kenceng",
        "Izinkan (nama orang) buat atur gaya rambutmu.",
        "Izinkan (nama orang) buat atur ulang make-up kamu.",
        "Harus menuruti semua perkataan (nama orang) selama 20 menit ke depan.",
        "Ulangi setiap perkataan orang yang ada di sampingmu sampai kamu dapat giliran lagi.",
        "Keluarkan semua isi tas, dompet, kantong, semua bawaan.",
        "all orang yang dipilih sama (nama orang) dan nyanyi Happy Birthday.",
        " Call orang yang sudah taken dan bilang kalau kamu suka sama pasangannya.",
        "G Publish karya apapun yang pernah kamu buat (bukan baru dibuat) ke InstaStory..",
        "Tiru gaya YouTuber atau TikToker sampai bisa ditebak orang lain.",
        "Coba salah satu tren TikTok atau dance TikTok dan upload ke InstaStory.",
        "Harus rela (nama orang) bikin tato pakai spidol permanen di area tubuh yang terlihat.",
        "Tunjukkan liked videos di TikTok/post yang disukai di Instagram.",
        "Tunjukkan daftar chat terakhir di WhatsApp/LINE..",
        "Tunjukkan history dari browser ponsel/laptop kamu..",
        "Tunjukkan history pencarian di Instagram/TikTok/LINE.",
        "Tunjukkan foto-foto/video paling baru di galeri.",
        "Push-up sekali setiap ada orang yang bilang “aku/gua/gw/ane” selama 10 menit ke depan..",
        "Lakukan rap gaya bebas selama 3 menit.",
        "Biarkan orang lain membuat status menggunakan akun sosial mediamu.",
        "Ungkapkan persaanmu kepada gebetanmu.",
        "Kayang selama satu menit.",
        "Baca dengan lantang pesan yang terakhir kali kamu kirim ke gebetanmu.",
        "Coba nyanyikan sebuah lagu untuk aku",
        "Tulis nama gebetan kamu di statusmu.",
        "Kirimkan aku foto kamu yang paling imut.",
        " Like dan share semua fotoku di Instagram.",
        "Tulis namaku di status WhatsApp-mu selama sehari.",
        " Unggah (posting) foto aku sebagai WhatsApp Story kamu.",
        "Coba telepon atau chat seseorang yang kamu taksir atau naksir kamu",
        "Aku tantang kamu untuk kirim foto selfie ke mantan, tunggu sampai dibuka dan kirim buktinya ke aku."

    ];

    var dare = dares[Math.floor(Math.random() * dares.length)];
    $("#result").html(dare);
});